### PR TITLE
Decouple schedule downloading from playback

### PR DESCRIPTION
**Pull request by mjs**
- Existing schedule will now be used even if there's no internet access
- Schedule will only be made active if all files for it have been
  downloaded
- New schedules are checked for at startup and then approx every
  hour (with random variation)
- Once playback of a schedule has begun it is not interrupted (may
  change this in the future but too hard with the current code structure)

### CODE REVIEW

**Comment by Davo36** [comment]
Looked at the Travis output.  There is one test failing and then some very long output.  Same lines being logged over and over again:


2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window
2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window
2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window
2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window
2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window
2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window
2019/09/30 04:31:20 Playing combo...
2019/09/30 04:31:20 Played last burst, sleeping until near end of window

Not sure what is going on there, or even if this is a problem.  I have downloaded the new code, built and am running it on the camera tonight.  Seems to be working OK...

**Comment by mjs** [comment]
@Davo36 I wasn't done with updating the tests yet. thanks for trying it out on your camera!

**Comment by Davo36** [comment]
@mjs Just went outside, it's playing sounds.  Output in the terminal seems correct too.

So, seems to be working fine.

**Comment by mjs** [comment]
@Davo36 there was a nasty pre-existing bug in the handling of the end of schedule which caused audiobait to unnecessarily spin in a tight loop. That was causing all the repeated test output but was also happening in practice. Fixed now.

**Comment by Davo36** [comment]
@mjs Nice one.

**Comment by mjs** [comment]
@davo36 thanks again for actually running the code tonight. It helps to have the extra confidence in these changes

**Pull request merged**
